# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ajw.io
title_separator: "-"
email: ajw@ajw.io
description: > # this means to ignore newlines until "baseurl:"
  Who neglects just one website anymore?
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ajw.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ajw
github_username: algrym
author:
  name: "A. J. Wright"
  location: "Knoxville, TN, USA"
  email: ajw@ajw.io
  github: algrym
  twitter: ajw
  mastodon:
  - username: ajw
  - instance: techhub.social
  feedburner : algrym
locale: "en-US"
subtitle: "Who neglects just one website anymore?"
github: [metadata]

social:
  type: Person
  links:
    - "https://techhub.social/@ajw"
    - "https://twitter.com/ajw"

# Build settings
markdown: kramdown
highlighter: rouge
# https://mmistakes.github.io/minimal-mistakes/docs/
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-sitemap

# "air", "aqua", "contrast", "dark", "default", "dirt", "neon", "mint", "plum", "sunrise"
minimal_mistakes_skin: "dark"
    
#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
show_downloads: false
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-50796794-1"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values: 
      layout: single
      show_title: true
      show_date: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
